### ISSUE TITLE
Unable to load custom sound

### ISSUE THREAD

**Issue by GarrettBlackmon** [petertalbanese/SoundSwapper#12]
Hello,

Cool project, I believe I am following the readme correctly but I think I have perhaps found some wav files that are unsupported in some way. I have confirmed this in the logs below.

[Here is a sample wav that produces this issue](https://easyupload.io/d4ulmi)

Though, through downloading wavs through various sources, I've not gotten one to work so perhaps its something specific to my system or configuration.

```
2023-07-24 11:31:52 CDT [AWT-EventQueue-0] WARN  com.soundswapper.SoundSwapperPlugin - Unable to load custom sound 2401
javax.sound.sampled.UnsupportedAudioFileException: Stream of unsupported format
	at java.desktop/javax.sound.sampled.AudioSystem.getAudioInputStream(Unknown Source)
	at com.soundswapper.SoundSwapperPlugin.tryLoadSound(SoundSwapperPlugin.java:270)
	at com.soundswapper.SoundSwapperPlugin.updateSoundList(SoundSwapperPlugin.java:299)
	at com.soundswapper.SoundSwapperPlugin.onConfigChanged(SoundSwapperPlugin.java:134)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.config.ConfigManager.setConfiguration(ConfigManager.java:824)
	at net.runelite.client.config.ConfigManager.setConfiguration(ConfigManager.java:841)
	at net.runelite.client.plugins.config.ConfigPanel.changeConfiguration(ConfigPanel.java:711)
	at net.runelite.client.plugins.config.ConfigPanel$2.focusLost(ConfigPanel.java:514)
	at java.desktop/java.awt.AWTEventMulticaster.focusLost(Unknown Source)
	at java.desktop/java.awt.Component.processFocusEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
	```

**Comment by petertalbanese** [comment]
Hey! That link you sent doesn't seem to work. Could you send the file again?

I've tested .wav files from a few different sites and haven't had issues yet. Also did things like youtube -> mp3 -> wav and still no problem. Where are you getting your files from?
